// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7iiaCTeUhxoBuVJVXvbszM0mofe1-bQg',
    appId: '1:419653793524:web:605135737762dd0e2fd0a1',
    messagingSenderId: '419653793524',
    projectId: 'kes1-4af3d',
    authDomain: 'kes1-4af3d.firebaseapp.com',
    storageBucket: 'kes1-4af3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xnsCkAkMx83KhpJn6QMBgG5kGqdOxjo',
    appId: '1:419653793524:android:6f4639babf20c7f82fd0a1',
    messagingSenderId: '419653793524',
    projectId: 'kes1-4af3d',
    storageBucket: 'kes1-4af3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8al31tTlqREWmcW_Rs_-3zKUBBfvPAKo',
    appId: '1:419653793524:ios:1764f0a16f59b3b22fd0a1',
    messagingSenderId: '419653793524',
    projectId: 'kes1-4af3d',
    storageBucket: 'kes1-4af3d.appspot.com',
    iosBundleId: 'com.example.ap4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8al31tTlqREWmcW_Rs_-3zKUBBfvPAKo',
    appId: '1:419653793524:ios:1764f0a16f59b3b22fd0a1',
    messagingSenderId: '419653793524',
    projectId: 'kes1-4af3d',
    storageBucket: 'kes1-4af3d.appspot.com',
    iosBundleId: 'com.example.ap4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7iiaCTeUhxoBuVJVXvbszM0mofe1-bQg',
    appId: '1:419653793524:web:e99b5f814091bb182fd0a1',
    messagingSenderId: '419653793524',
    projectId: 'kes1-4af3d',
    authDomain: 'kes1-4af3d.firebaseapp.com',
    storageBucket: 'kes1-4af3d.appspot.com',
  );
}
